"""empty message

Revision ID: 57121e2faebf
Revises: 1419b9d8cc01
Create Date: 2024-09-14 16:51:20.215786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57121e2faebf'
down_revision = '1419b9d8cc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
